//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DroneMainAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annoucement
    {
        public int NewId { get; set; }
        public string NewTittle { get; set; }
        public string NewMessage { get; set; }
        public string ImageIcon { get; set; }
        public string tagName { get; set; }
        public Nullable<bool> isDelete { get; set; }
    }
}
