//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DroneMainAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailType
    {
        public int Id { get; set; }
        public Nullable<System.Guid> UniId { get; set; }
        public string DisplayName { get; set; }
        public string Subjectmsg { get; set; }
        public string BodyMsg { get; set; }
    }
}
