//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DroneMainAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string EmailID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Password { get; set; }
        public string ContactNo { get; set; }
        public string AddresL { get; set; }
        public string Street { get; set; }
        public string CityName { get; set; }
        public string Provinance { get; set; }
        public string CountryName { get; set; }
        public bool IsEmailVerified { get; set; }
        public bool TermsAccepted { get; set; }
        public bool SubEmail { get; set; }
        public System.Guid ActivationCode { get; set; }
        public bool Visachk { get; set; }
        public bool Nocchk { get; set; }
        public bool AdminType { get; set; }
        public string TeamName { get; set; }
        public string Decscript { get; set; }
        public string Pincode { get; set; }
        public System.Guid GlobalID { get; set; }
    }
}
